### ISSUE TITLE
Diffuse Card & GUI

### ISSUE THREAD

**Issue by JenniferBrana** [ayrjanson/GameFramework#2]
Playing a diffuse card ends the game and causes you to lose. 

Additionally, the GUI doesn't display all cards in the humans hand and the controls to scroll through are not very intuitive or clear. Using a scroll bar or putting all the cards on the screen would help.

**Comment by ayrjanson** [comment]
Resolution:
- Found the problematic conditional statement that triggered the player to lose if they tried to play a defuse card. That statement has been changed to send the user that specific condition when they try to play a defuse card
- Working on creating a more intuitive GUI layout for cards by using tab right and left buttons that now display a message in a text view if there are no more cards to display in either direction
